apiVersion: v1
kind: Namespace
metadata:
  name: workshop

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: front-config
  namespace: workshop
data:
  BANNER_TEXT: "Bienvenue sur le front"

---

apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: workshop
type: Opaque
stringData:
  FRONT_SECRET: "front123"
  API_SECRET: "api123"

---

apiVersion: v1
kind: Secret
metadata:
  name: ghcr-creds
  namespace: workshop
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: <base64_encoded_docker_config>

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
  namespace: workshop
spec:
  replicas: 2
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
        - name: front
          image: ghcr.io/nginxdemos/hello:plain-text
          ports:
            - containerPort: 80
          env:
            - name: BANNER_TEXT
              valueFrom:
                configMapKeyRef:
                  name: front-config
                  key: BANNER_TEXT
      imagePullSecrets:
        - name: ghcr-creds

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: workshop
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: kennethreitz/httpbin:latest
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: ghcr-creds

---

apiVersion: v1
kind: Service
metadata:
  name: front
  namespace: workshop
spec:
  selector:
    app: front
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: workshop
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

---

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned
spec:
  selfSigned: {}

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web
  namespace: workshop
spec:
  ingressClassName: nginx
  rules:
    - host: workshop.local
      http:
        paths:
          - path: /front
            pathType: Prefix
            backend:
              service:
                name: front
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: 80
  tls:
    - hosts:
        - workshop.local
      secretName: workshop-tls
